#!/bin/bash

set -e

op="$1"
sub="$2"
SETTINGS_DIR="$HOME/.aws_cred_man"
AWS_CREDS="$HOME/.aws/credentials"

function main() {
    validate_usage

    initialize

    # list command
    if [[ $op == "list" || $op == "ls" ]]; then 
        cur=$(readlink ~/.aws/credentials | xargs basename)
        ls -1 $SETTINGS_DIR | xargs -I {} -n1 bash -c "if [ \"${cur}\" == {} ]; then echo \"* {}\" ;  else echo \"  {}\" ; fi"
    fi

    # cat
    if [[ $op == "cat" ]]; then 
        if [ -z $sub]; then
            cat $AWS_CREDS
        else
            cat "$SETTINGS_DIR/$sub"
        fi
        
    fi

    # current command
    if [[ $op == "current" || $op == "cur" ]]; then 
        readlink ~/.aws/credentials | xargs basename
    fi

    # remove command
    if [[ $op == "remove" || $op == "rm" ]]; then 
        if [ -z "$sub" ]; then 
            echo "settings name required $op <settings>" && exit 1
        fi
        rm "$SETTINGS_DIR/$sub"
    fi

    # use command
    if [[ $op == "use" ]]; then 
        if [ -z "$sub" ]; then 
            echo "settings name required $op <settings>" && exit 1
        fi
        settings="$SETTINGS_DIR/$sub"

        if [ ! -f "$settings" ]; then
            echo "settings $sub does not exist" && exit 1
        fi

        rm $AWS_CREDS
        ln -s $settings $AWS_CREDS
    fi

    # edit or create command
    if [[ $op == "edit" || $op == "create" ]]; then 
        if [ -z "$sub" ]; then 
            if [ "$op" == "create" ]; then 
                echo "settings name required. try 'edit <settings>'" && exit 1
            fi
            sub=$(readlink ~/.aws/credentials | xargs basename)
            echo here  $sub ll
            if [ -z "$sub" ]; then
                sub="default"
            fi
        fi
        
        # create settings
        settings=$SETTINGS_DIR/$sub
        if [ ! -f "$settings" ]; then
            touch $settings
        fi
        vi $settings
    fi
}

function usage() {
    width=25
    echo
    echo "Credentials Manager for AWS (v1.0.0)"
    echo
    echo "Usage"
    printf '  ls\t%s\n' 'list settings' | expand -t $width
    printf '  current\t%s\n' 'show the current settings' | expand -t $width
    printf '  use <settings>\t%s\n' 'switch to <settings>' | expand -t $width
    printf '  create <settings>\t%s\n' 'create/edit <settings>' | expand -t $width
    printf '  rm <settings>\t%s\n' 'remove the <settings>' | expand -t $width
    printf '  edit <settings>\t%s\n' 'create/edit <settings>' | expand -t $width
    printf '  help\t%s\n' 'show this message' | expand -t $width

    echo
}

function validate_usage() {
    valid_ops="cat create current cur edit list ls remove rm use"
    if [[ ! " ${valid_ops[@]} " =~ " ${op} " ]]; then
        usage
        exit 1
    fi
}

function initialize() {
    # create config dir
    if [ ! -d "$SETTINGS_DIR" ]; then
        mkdir -p SETTINGS_DIR
    fi

    # setup
    # if aws creds does not exist or is not a symbolic link, we have work to do
    if [ ! -L "$AWS_CREDS" ]; then
        # if it exists move it and set it as the default settings
        if [ -f "$AWS_CREDS" ]; then
            default="$SETTINGS_DIR/default"
            mv $AWS_CREDS $default
            ln -s $default $AWS_CREDS
            echo "Your're all set up and good to go!"
            echo "Here's what changed"
            echo "=> moved $AWS_CREDS to $default"
            echo "=> symlinked $AWS_CREDS to $default"
        fi
    fi
}

main "$@"; exit